spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mybatis_db
    username: postgres
    password: 8023cc
mybatis:
  mapper-locations: classpath:mapper/*.xml
springdoc:
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: '智慧交通后台'
      paths-to-match: '/**'
      packages-to-scan: com.chauncey
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
