
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smart_traffic
    username: postgres
    password: 8023cc
  servlet:
    multipart:
      max-file-size: 2MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换
springdoc:
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: '智慧交通后台'
      paths-to-match: '/**'
      packages-to-scan: com.chauncey
knife4j:
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  enable: true
server:
  port: 8090
cloud:
  server:
    host: 122.51.167.25
    port: 22
    username: ubuntu
    password: 8023CC1129hh
    remoteDir: /home/ubuntu/img_upload
